spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
# 로컬
app:
  oauth2:
    redirect-uri:
      success: http://localhost:3000/oauth2/callback
      failure: http://localhost:3000/login
server:
  port: 8080